defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "docs"
    values:
      layout: docs
      tab: docs

sass:
  sass_dir: _sass
  style: :compressed

baseurl: "/jenkins-dcos"
encoding: ASCII-8BIT
highlighter: rouge
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
safe: true
source: .
